export const publicAssets = {
  site: {
    appleTouchIcon: 'apple-touch-icon.png',
    favicon: 'favicon.ico',
    favicon16: 'favicon-16x16.png',
    favicon32: 'favicon-32x32.png',
    faviconDark16: 'favicon-dark-16x16.png',
    faviconDark32: 'favicon-dark-32x32.png',
    googleSiteVerification: 'googlebc556dca81677489.html',
    ogImage: 'og-image.png',
    robots: 'robots.txt',
  },
  documents: {
    resume: {
      en: 'documents/resume/CV_LuongDucTrong_FrontendDeveloper.pdf',
      vi: 'documents/resume/CV_LuongDucTrong_LapTrinhVienFrontend.pdf',
    },
  },
  projects: {
    funnyCode: {
      cover: 'images/projects/re-funnycode-frontend/funnycode-cover.png',
      image1: 'images/projects/re-funnycode-frontend/funnycode-1.png',
      image2: 'images/projects/re-funnycode-frontend/funnycode-2.png',
      image3: 'images/projects/re-funnycode-frontend/funnycode-3.png',
      image4: 'images/projects/re-funnycode-frontend/funnycode-4.png',
      thumbnail1: 'images/projects/re-funnycode-frontend/thumbnail-1.png',
      thumbnail2: 'images/projects/re-funnycode-frontend/thumbnail-2.png',
      thumbnail3: 'images/projects/re-funnycode-frontend/thumbnail-3.png',
      thumbnail4: 'images/projects/re-funnycode-frontend/thumbnail-4.png',
    },
    game2048: {
      cover: 'images/projects/game-2048/game-cover.png',
      image1: 'images/projects/game-2048/game-1.png',
      image2: 'images/projects/game-2048/game-2.png',
      image3: 'images/projects/game-2048/game-3.png',
      image4: 'images/projects/game-2048/game-4.png',
      thumbnail1: 'images/projects/game-2048/thumbnail-1.png',
      thumbnail2: 'images/projects/game-2048/thumbnail-2.png',
      thumbnail3: 'images/projects/game-2048/thumbnail-3.png',
      thumbnail4: 'images/projects/game-2048/thumbnail-4.png',
    },
    portfolioV2: {
      cover: 'images/projects/portfolio-v2/portfolio-cover.png',
      image1: 'images/projects/portfolio-v2/portfolio-1.png',
      image2: 'images/projects/portfolio-v2/portfolio-2.png',
      image3: 'images/projects/portfolio-v2/portfolio-3.png',
      image4: 'images/projects/portfolio-v2/portfolio-4.png',
      thumbnail1: 'images/projects/portfolio-v2/thumbnail-1.png',
      thumbnail2: 'images/projects/portfolio-v2/thumbnail-2.png',
      thumbnail3: 'images/projects/portfolio-v2/thumbnail-3.png',
      thumbnail4: 'images/projects/portfolio-v2/thumbnail-4.png',
    },
    reactFioriStyle: {
      cover: 'images/projects/react-fiori-style/fiori-cover.png',
      image1: 'images/projects/react-fiori-style/fiori-1.png',
      image2: 'images/projects/react-fiori-style/fiori-2.png',
      image3: 'images/projects/react-fiori-style/fiori-3.png',
      image4: 'images/projects/react-fiori-style/fiori-4.png',
      thumbnail1: 'images/projects/react-fiori-style/thumbnail-1.png',
      thumbnail2: 'images/projects/react-fiori-style/thumbnail-2.png',
      thumbnail3: 'images/projects/react-fiori-style/thumbnail-3.png',
      thumbnail4: 'images/projects/react-fiori-style/thumbnail-4.png',
    },
  },
} as const;
